/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.MarketingRole;

import Business.BiedgeBuyingSystem;
import Business.Customer.Customer;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Organization.MarketingOrganization;
import Business.Organization.Organization;
import Business.Product.Product;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import userinterface.AdministrativeRole.ManageEmployeeJPanel;

/**
 *
 * @author vanit
 */
public class MarketingAllTaskJPanel extends javax.swing.JPanel {

    /**
     * Creates new form MarketingAllTaskJPanel
     */
    private JPanel userProcessContainer;
    private BiedgeBuyingSystem system;
    private Enterprise enterprise;
    private Employee employee;
    private ArrayList<Product> productList;
    
    public MarketingAllTaskJPanel(JPanel userProcessContainer,BiedgeBuyingSystem system ,Enterprise enterprise,  Employee employee) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.enterprise = enterprise;
        this.employee = employee;
        this.productList = employee.getProductList();
        
        populateTable1();
        populateCombox();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSubmit = new javax.swing.JButton();
        btnBack1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtTracking = new javax.swing.JTextField();
        btnUpdate1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        marketingTbl = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        customerjComboBox3 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        btnSubmit.setBackground(new java.awt.Color(153, 153, 255));
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        btnBack1.setBackground(new java.awt.Color(153, 153, 255));
        btnBack1.setText("< Back");
        btnBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Expert Index:");

        btnUpdate1.setBackground(new java.awt.Color(153, 153, 255));
        btnUpdate1.setText("Update");
        btnUpdate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdate1ActionPerformed(evt);
            }
        });

        marketingTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Prod ID", "Name", "Sales Price", "Quantity", "Sales Volume", "Delivery Date", "Expert Index", "Recommendation Index", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(marketingTbl);

        jButton1.setBackground(new java.awt.Color(153, 153, 255));
        jButton1.setText("Management Customer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        customerjComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        customerjComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerjComboBox3ActionPerformed(evt);
            }
        });

        jLabel3.setText("CustomerEmail");

        jTextField1.setEditable(false);
        jTextField1.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(btnBack1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)))
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSubmit)
                                .addGap(45, 45, 45)
                                .addComponent(customerjComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(99, 99, 99)))
                        .addGap(61, 61, 61)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtTracking, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnUpdate1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(jButton1)))
                .addGap(137, 380, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTracking, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(btnUpdate1))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerjComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSubmit))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(btnBack1)
                .addGap(83, 83, 83)
                .addComponent(jButton1)
                .addGap(28, 28, 28))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void populateCombox()
    {
        customerjComboBox3.removeAllItems();
        
        for(Map.Entry<String, Customer> customers : enterprise.getOrganizationDirectory().
                getOrganizationTypeMap().get(Organization.Type.Marketing).getCustomerEmailMap().
                entrySet())
        {
            
            String customer = customers.getValue().getName() + "(" +  customers.getKey() + ")";
            customerjComboBox3.addItem(customer);
        }
    }
    
    public void populateTable1()
    {
        int index = 0;

        DefaultTableModel dtm = (DefaultTableModel) marketingTbl.getModel();
        dtm.setRowCount(0);
        for(int i=0;i< productList.size();i++)
        {
            Product product = productList.get(i);
            Object[] row = new Object[8];
            row[0] = product.getProductID();
            row[1] = product.getProductName();
            row[2] = product.getSalesPrice();
            row[3] = product.getQuantity();
            row[4] = product.getSalesVolume();
            row[5] = product.getDeliveryDate();
            row[6] = index;            
            row[7] = index * product.getSalesVolume();
            
            product.setExpertIndex(index);
            product.setRecommendationIndex(index * product.getSalesVolume());
            productList.set(i, product);
            dtm.addRow(row);
        }
    }
    
    private void populateTable()
    {
        int index = 0;
        if(!txtTracking.getText().equals(""))
        {
            try{


                    Integer.parseInt(txtTracking.getText());
                    

            }catch(NumberFormatException e){
                JOptionPane.showMessageDialog(null, "Please try in 1,3,5,7, or 9 for index!");
                return;
            }
            
            index = Integer.parseInt(txtTracking.getText());
            if((index != 1) && (index != 3) && (index != 5) && (index != 7) && (index != 9))
            {
                JOptionPane.showMessageDialog(null, "Please try in 1,3,5,7, or 9 for index!");
                return;
            }
        }else {
            JOptionPane.showMessageDialog(null, "Please try in a 1,3,5,7, or 9 for index!");
                return;
        }

        DefaultTableModel dtm = (DefaultTableModel) marketingTbl.getModel();
        dtm.setRowCount(0);
        for(int i=0;i< productList.size();i++)
        {
            Product product = productList.get(i);
            Object[] row = new Object[9];
            row[0] = product.getProductID();
            row[1] = product.getProductName();
            row[2] = product.getSalesPrice();
            row[3] = product.getQuantity();
            row[4] = product.getSalesVolume();
            row[5] = product.getDeliveryDate();
            row[6] = index;            
            row[7] = index * product.getSalesVolume();
            row[8] = "Index Updated";
            
            product.setExpertIndex(index);
            product.setRecommendationIndex(index * product.getSalesVolume());
            productList.set(i, product);
            dtm.addRow(row);
        }
    }
    
    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        if(jTextField1.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Submit fail! ");
            return;
        }
        String customerEmail = jTextField1.getText();
        Customer customerTemp = system.getNetworkMap().get(enterprise.getNetworkName()).getEnterpriseDirectory().
                getEnterpriseNameMap().get(enterprise.getName()).getOrganizationDirectory().
                getOrganizationTypeMap().get(Organization.Type.Marketing).getCustomerEmailMap().get(customerEmail);
        customerTemp.setProductList(productList);
        system.getNetworkMap().get(enterprise.getNetworkName()).getEnterpriseDirectory().
                getEnterpriseNameMap().get(enterprise.getName()).getOrganizationDirectory().
                getOrganizationTypeMap().get(Organization.Type.Marketing).getCustomerEmailMap().put(customerEmail, customerTemp);
        
        JOptionPane.showMessageDialog(null, "Submit successfully! ");
        
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBack1ActionPerformed

    private void btnUpdate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdate1ActionPerformed
        // TODO add your handling code here:
        
        
        populateTable();
        
        
    }//GEN-LAST:event_btnUpdate1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ManageCustomerJPanel manageCustomerJPanel = new ManageCustomerJPanel(userProcessContainer, 
                system, enterprise.getOrganizationDirectory().getOrganizationTypeMap().get(Organization.Type.Marketing),
        enterprise, employee);
        userProcessContainer.add("manageEmployeeJPanel", manageCustomerJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void customerjComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerjComboBox3ActionPerformed
        // TODO add your handling code here:
        String name3 = (String) customerjComboBox3.getSelectedItem();
        

        if(name3== null)
            return;
        else {
            
            String ecustomerEmail = name3.substring(name3.indexOf("(") + 1, name3.length() - 1);

            jTextField1.setText(ecustomerEmail);
            
        }
    }//GEN-LAST:event_customerjComboBox3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack1;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton btnUpdate1;
    private javax.swing.JComboBox<String> customerjComboBox3;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable marketingTbl;
    private javax.swing.JTextField txtTracking;
    // End of variables declaration//GEN-END:variables
}
