/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.ShippingRole;

import Business.BiedgeBuyingSystem;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Order.Order;
import Business.Organization.ShippingManagementOrganization;
import Business.Product.Product;
import Business.UserAccount.UserAccount;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vanit
 */
public class ShippingAllTaskJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ShippingAllTaskJPanel
     */
    private JPanel userProcessContainer;
    private BiedgeBuyingSystem system;
    private Enterprise enterprise;
    private Employee employee;
    private ArrayList<Order> orderList;

    public ShippingAllTaskJPanel(JPanel userProcessContainer, BiedgeBuyingSystem system, Enterprise enterprise, Employee employee) {
            initComponents();
            this.userProcessContainer = userProcessContainer;
            this.system = system;
            this.enterprise = enterprise;
            this.employee = employee;
            orderList = employee.getOrderList();
            populateTable();
    }

    private void populateTable()
    {
        String trackingNo = txtTracking.getText();
        DefaultTableModel dtm = (DefaultTableModel) shippingTbl.getModel();
        dtm.setRowCount(0);
        for(int i=0;i < orderList.size();i++)
        {
            Order order = orderList.get(i);
            Object[] row = new Object[9];
            row[0] = order.getOrderID();
            row[1] = order.getSalesman();
            row[2] = order.getCustomer().getCustomerID();
            row[3] = order.getProductID();
            row[4] = order.getSalesPrice();
            row[5] = order.getQuantity();
            if(!trackingNo.equals(""))
                row[6] = trackingNo;
            row[7] = order.getTotalPrice();
            row[8] = "Tracking generated";
            dtm.addRow(row);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        shippingTbl = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtTracking = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();

        shippingTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order ID", "Salesman", "Customer ID", "Prod ID", "Sales Price", "Quantity", "Tracking No.", "Total Price", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(shippingTbl);
        if (shippingTbl.getColumnModel().getColumnCount() > 0) {
            shippingTbl.getColumnModel().getColumn(0).setResizable(false);
            shippingTbl.getColumnModel().getColumn(1).setResizable(false);
            shippingTbl.getColumnModel().getColumn(2).setResizable(false);
            shippingTbl.getColumnModel().getColumn(3).setResizable(false);
            shippingTbl.getColumnModel().getColumn(4).setResizable(false);
            shippingTbl.getColumnModel().getColumn(5).setResizable(false);
            shippingTbl.getColumnModel().getColumn(6).setResizable(false);
            shippingTbl.getColumnModel().getColumn(7).setResizable(false);
        }

        jLabel1.setText("Tracking Number: ");

        btnUpdate.setBackground(new java.awt.Color(153, 153, 255));
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 849, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(txtTracking, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnUpdate)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTracking, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate))
                .addContainerGap(316, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        
        populateTable();
    }//GEN-LAST:event_btnUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable shippingTbl;
    private javax.swing.JTextField txtTracking;
    // End of variables declaration//GEN-END:variables
}
