/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.AccountsRole;

import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Order.Order;
import Business.Organization.AccountingOrganization;
import Business.UserAccount.UserAccount;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vanit
 */
public class AccountingAllTaskJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AccountingAllTaskJPanel
     */
    private JPanel userProcessContainer;
    private Employee employee;
    private ArrayList<Order> orderList;
   
    public AccountingAllTaskJPanel(JPanel userProcessContainer, Employee employee) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.employee = employee;
        this.orderList = employee.getOrderList();
        
        populateTable();
    }
    
    private void populateTable()
    {
        DefaultTableModel dtm = (DefaultTableModel) accountTbl.getModel();
        dtm.setRowCount(0);
        for(int i=0;i < orderList.size();i++)
        {
            Order order = orderList.get(i);
            Object[] row = new Object[8];
            row[0] = order.getOrderID();
            
            row[1] = order.getCustomer().getCustomerID();
            row[2] = order.getProductID();
            row[3] = order.getSalesPrice();
            row[4] = order.getQuantity();
            row[5] = 0;
            row[6] = 0;
            row[7] = 0;
            dtm.addRow(row);
        }
    }

    private void populateTable2()
    {
        DefaultTableModel dtm = (DefaultTableModel) accountTbl.getModel();
        dtm.setRowCount(0);
        for(int i=0;i < orderList.size();i++)
        {
            Order order = orderList.get(i);
            Object[] row = new Object[9];
            row[0] = order.getOrderID();
            
            row[1] = order.getCustomer().getCustomerID();
            row[2] = order.getProductID();
            row[3] = order.getSalesPrice();
            row[4] = order.getQuantity();
            row[5] = order.getTotalPrice()*0.1;
            row[6] = order.getTotalPrice()*0.04;
            row[7] = order.getTotalPrice()*0.06;
            row[8] = "Profit calculated";
            dtm.addRow(row);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        accountTbl = new javax.swing.JTable();
        btnCalculate = new javax.swing.JButton();
        btnBack1 = new javax.swing.JButton();

        accountTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order ID", "Customer ID", "Prod ID", "Sales Price", "Quantity", "Total Revenue", "Rev. Consulting company", "Rev. Buying Agent", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(accountTbl);
        if (accountTbl.getColumnModel().getColumnCount() > 0) {
            accountTbl.getColumnModel().getColumn(0).setResizable(false);
            accountTbl.getColumnModel().getColumn(1).setResizable(false);
            accountTbl.getColumnModel().getColumn(2).setResizable(false);
            accountTbl.getColumnModel().getColumn(3).setResizable(false);
            accountTbl.getColumnModel().getColumn(4).setResizable(false);
            accountTbl.getColumnModel().getColumn(5).setResizable(false);
            accountTbl.getColumnModel().getColumn(6).setResizable(false);
            accountTbl.getColumnModel().getColumn(7).setResizable(false);
        }

        btnCalculate.setBackground(new java.awt.Color(153, 153, 255));
        btnCalculate.setText("Calculate");
        btnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateActionPerformed(evt);
            }
        });

        btnBack1.setBackground(new java.awt.Color(153, 153, 255));
        btnBack1.setText("< Back");
        btnBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 867, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(btnBack1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(btnCalculate)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(btnCalculate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 353, Short.MAX_VALUE)
                .addComponent(btnBack1)
                .addGap(140, 140, 140))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed
        // TODO add your handling code here:
        populateTable2();
    }//GEN-LAST:event_btnCalculateActionPerformed

    private void btnBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBack1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable accountTbl;
    private javax.swing.JButton btnBack1;
    private javax.swing.JButton btnCalculate;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
